const mongoose = require('mongoose');

const saleItemSchema = new mongoose.Schema({
    product: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Product',
        required: true
    },
    productName: String,
    sku: String,
    quantity: {
        type: Number,
        required: true,
        min: 1
    },
    unitPrice: {
        type: Number,
        required: true,
        min: 0
    },
    subtotal: {
        type: Number,
        required: true,
        min: 0
    },
    discount: {
        type: Number,
        default: 0,
        min: 0
    }
});

const saleSchema = new mongoose.Schema({
    invoiceNumber: {
        type: String,
        unique: true,
        sparse: true  // Allow null until generated by pre-save hook
    },
    items: [saleItemSchema],
    subtotal: {
        type: Number,
        required: true,
        min: 0
    },
    tax: {
        type: Number,
        default: 0,
        min: 0
    },
    discount: {
        type: Number,
        default: 0,
        min: 0
    },
    total: {
        type: Number,
        required: true,
        min: 0
    },
    paymentMethod: {
        type: String,
        enum: ['cash', 'card', 'upi', 'cheque', 'bank_transfer'],
        required: true
    },
    paymentStatus: {
        type: String,
        enum: ['paid', 'pending', 'partial', 'refunded'],
        default: 'paid'
    },
    amountPaid: {
        type: Number,
        default: 0
    },
    amountDue: {
        type: Number,
        default: 0
    },
    customer: {
        name: {
            type: String,
            required: true
        },
        phone: String,
        email: String,
        address: String,
        gstNumber: String
    },
    soldBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },
    notes: String,
    status: {
        type: String,
        enum: ['completed', 'cancelled', 'refunded'],
        default: 'completed'
    }
}, {
    timestamps: true
});

// Generate invoice number before saving
saleSchema.pre('save', async function (next) {
    if (this.isNew && !this.invoiceNumber) {
        const date = new Date();
        const year = date.getFullYear().toString().substr(-2);
        const month = (date.getMonth() + 1).toString().padStart(2, '0');
        const count = await this.constructor.countDocuments();
        this.invoiceNumber = `INV-${year}${month}-${(count + 1).toString().padStart(5, '0')}`;
    }
    next();
});

module.exports = mongoose.model('Sale', saleSchema);
